---
title: "Worksheet-1 in R"
author: "Jared J Basa"
date: "09-04-2024"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
1.Vector Age
```{r}
age_ <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27, 22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 42, 53, 41,
51, 35, 24, 33, 41.)
length(age_)
```
2.Reciprocal Age
```{r}
age_ <-c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27, 22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 42, 53, 41,
51, 35, 24, 33, 41.)
recipro_age <- 1/age_
print(recipro_age)
```
3.New Age
```{r}
age_ <-c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27, 22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 42, 53, 41,
51, 35, 24, 33, 41.)
new_age <-c (age_, 0, age_)
print(new_age)
```
4.Sort Val. Age
```{r}
age_ <-c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27, 22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 42, 53, 41,
51, 35, 24, 33, 41.)
sort_age <- sort(age_)
print(sort_age)
```
Min and Max Age
```{r}
age_ <-c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27, 22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 42, 53, 41,
51, 35, 24, 33, 41.)
min_age <- min(age_)
max_age <- max(age_)
print(min_age)
print(max_age)
```
6. 2nd Data Set
```{r}
data_ <- c(2.4, 2.8, 2.1, 2.5, 2.4, 2.2, 2.5,
2.3, 2.5, 2.3, 2.4, 2.7)
length(data_)
```
7. Doubled Data
```{r}
data_ <- c(2.4, 2.8, 2.1, 2.5, 2.4, 2.2, 2.5,
2.3, 2.5, 2.3, 2.4, 2.7)
data_doubled <- data_*2
print(data_doubled)
```
8. Sequence
+ 8.1
```{r}
seq(1:100)
```
+ 8.2
```{r}
seq(20:60)
```
+ 8.3
```{r}
mean(20:60)
```
8.4
```{r}
sum(51:91)
```
8.5
```{r}
seq(1:1000)
```
9. Filter
```{r}
Filter(function(i) { all(i %% c(3,5,7) != 0) }, seq(100))
```
10. Backward
```{r}
rev(1:100)
```
11. List all the natural members below 25 that are multiple of 3 and 5
```{r}
nums <- 1:25
multiples <- nums[nums %% 3 == 0 | nums %% 5 == 0]
print(multiples)
sum(multiples)
```
11.a
```{r}
startpoint <- 10
endpoint <- 11

datapoints <- seq(startpoint, endpoint)
print(datapoints)
numdata <- length(startpoint:endpoint)
print(numdata)
```
12. Statements
```{r}
x <- {0 + x + 5 +}
```
13. *Set up a vector named score, consisting of 72, 86, 92, 63, 88, 89, 91, 92, 75,
75 and 77. To access individual elements of an atomic vector, one generally uses the
x[i] construction.
Find x[2] and x[3]. Write the R code and its output.
```{r}
score <- c(72, 86, 92, 63, 88, 89, 91, 92, 75, 75,77)
score[2]
score[3]
```





